// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	authsvc "github.com/alextanhongpin/go-service-oriented-package/app/authsvc"

	mock "github.com/stretchr/testify/mock"
)

// LoginRepo is an autogenerated mock type for the loginRepo type
type LoginRepo[T interface{}] struct {
	mock.Mock
}

// FindUserByEmail provides a mock function with given fields: ctx, email
func (_m *LoginRepo[T]) FindUserByEmail(ctx context.Context, email string) (*authsvc.User[T], error) {
	ret := _m.Called(ctx, email)

	var r0 *authsvc.User[T]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*authsvc.User[T], error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *authsvc.User[T]); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authsvc.User[T])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewLoginRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewLoginRepo creates a new instance of LoginRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLoginRepo[T interface{}](t mockConstructorTestingTNewLoginRepo) *LoginRepo[T] {
	mock := &LoginRepo[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
